version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9870:9870
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hive-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hive-net
    depends_on:
      - namenode

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=metastore-postgres
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - 9083:9083
    networks:
      - hive-net
    depends_on:
      - namenode
      - datanode
      - metastore-postgres

  metastore-postgres:
    image: postgres:13
    container_name: metastore-postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - 5432:5432
    networks:
      - hive-net
    volumes:
      - metastore-postgres:/var/lib/postgresql/data

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - 10000:10000
      - 10002:10002
    networks:
      - hive-net
    depends_on:
      - hive-metastore

  hive-cli:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-cli
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
    environment:
      - HIVE_SERVER2_THRIFT_URL=jdbc:hive2://hive-server:10000/default
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./hive_scripts.sql:/hive_scripts.sql
      - ./dataset_ventas.csv:/dataset_ventas.csv
      - ./scripts/entrypoint.sh:/scripts/entrypoint.sh
    networks:
      - hive-net
    depends_on:
      - hive-server

volumes:
  namenode:
  datanode:
  metastore-postgres:

networks:
  hive-net:
    driver: bridge